### ISSUE TITLE
Screenshots Wanted

### ISSUE THREAD

**Issue by michael-spengler** [Ethernol/C2H6O#4]
Hey Leute. Könnt Ihr Eure Readme aufwerten, indem Ihr Screenshots und eine Beschreibung zum Sinn und Zweck des Projektes hinzufügt?

Das wäre m.E. hilfreich für Besucher und mögliche Contributors...

**Comment by EinePriseCode** [comment]
Hi. Wir haben irgendwie alle keine Benachrichtigung für den Issue bekommen bzw wahrgenommen und waren mit unseren Studienarbeiten und dann der Arbeit in der Paxisphase so beschäftigt, dass wir nicht nochmal in das Repo geschaut haben.
Wir fügen die verschiedenen Punkte noch hinzu.
